# Generated by Django 4.0.4 on 2022-05-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabata', '0002_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='article',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
