# Generated by Django 4.0.4 on 2022-05-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabata', '0004_alter_training_title_usertraining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
