# Generated by Django 4.0.4 on 2022-06-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabata', '0009_remove_article_title_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalConsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField()),
            ],
        ),
    ]
