# Generated by Django 4.0.4 on 2022-06-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabata', '0010_personalconsert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalconsert',
            name='title',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
